config/routes.rb
Rails.application.routes.draw do

  get 'compare' => 'compare#index'
  get 'cart' => 'cart#index'
  get 'checkout' => 'checkout#index'

  get 'account' => 'account#dashboard'
  get 'account/profile' => 'account#profile'
  get 'account/orders' => 'account#orders'
  get 'account/orders/:id' => 'account#order'
  get 'account/subscriptions' => 'account#subscriptions'
  get 'account/reviews' => 'account#reviews'
  get 'account/wishlist' => 'account#wishlist'

  get 'login' => 'account#login'

  get 'about-us'=> 'static#about_us', as: 'about_us'
  get 'faq' => 'static#faq'
  get 'how-to-order' => 'static#how_to_order', as: 'how_to'
  get 'warranty' => 'static#warranty'
  get 'contact-us' => 'static#contact', as: 'contacts'
  get 'terms-and-conditions' => 'static#terms', as: 'terms'

  get 'product/quick_view' => 'product#view', as: 'product_view'
  get 'product/:id' => 'product#show'
  get 'categories' => 'category#index'
  get 'category/:id' => 'category#show'

  root 'home#index'

  devise_for :accounts

  mount Colibri::Core::Engine => '/shop', as: 'colibri'
  mount Ckeditor::Engine => '/ckeditor'
  mount RailsAdmin::Engine => '/editor', as: 'rails_admin'
end

app/models/account.rb
class Account < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :confirmable, :lockable, :timeoutable, :omniauthable
end

app/models/ckeditor/asset.rb
class Ckeditor::Asset < ActiveRecord::Base
  include Ckeditor::Orm::ActiveRecord::AssetBase
  include Ckeditor::Backend::Paperclip
end

app/controllers/account_controller.rb
class AccountController < ApplicationController
  def dashboard
  end

  def profile
  end

  def orders
  end

  def order
  end

  def subscriptions
  end

  def reviews
  end

  def wishlist
  end

  def login
    respond_to do |format|
      format.html { render :layout => !request.xhr? }
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/cart_controller.rb
class CartController < ApplicationController
  def index
  end
end

app/controllers/category_controller.rb
class CategoryController < ApplicationController
  def index
  end

  def show
  end
end

app/controllers/checkout_controller.rb
class CheckoutController < ApplicationController
  def index

  end
end

app/controllers/compare_controller.rb
class CompareController < ApplicationController
  def index
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/product_controller.rb
class ProductController < ApplicationController
  def show
  end

  def view
    respond_to do |format|
      format.html { render :layout => !request.xhr? }
    end
  end
end

app/controllers/static_controller.rb
class StaticController < ApplicationController
  def about_us
  end

  def faq
  end

  def how_to_order
  end

  def warranty
  end

  def contact
  end

  def terms
  end
end

app/helpers/account_helper.rb
module AccountHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cart_helper.rb
module CartHelper
end

app/helpers/category_helper.rb
module CategoryHelper
end

app/helpers/checkout_helper.rb
module CheckoutHelper
end

app/helpers/compare_helper.rb
module CompareHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/product_helper.rb
module ProductHelper
end

app/helpers/static_helper.rb
module StaticHelper
end

app/views/layouts/account.html.erb
<% content_for :container do %>
    <div class="secondary_page_wrapper">
      <div class="container">

        <%= render partial: "shared/breadcrumbs" %>
        <div class="row">

          <aside class="col-md-3 col-sm-4">

            <%= render partial: "sidebar_menu" %>

            <%= yield :sidebar if content_for? :sidebar %>

            <div class="section_offset">
              <a href="#" class="banner">
                <img src="/static/images/banner_img_3.jpg" alt="">
              </a>
            </div>

          </aside>

          <main class="col-md-9 col-sm-8">

            <%= yield :cta if content_for? :cta %>

            <%= yield %>
          </main>

        </div><!--/ .row-->

      </div>
    </div>
<% end  %>

<% content_for :stylesheets do %>
    <link rel="stylesheet" href="/static/css/jquery-ui.min.css">
<% end %>

<% content_for :javascripts do %>
    <script src="/static/js/jquery-ui.min.js"></script>
<% end %>

<% content_for :footer do %>
    <%= render partial: 'shared/features_block' %>
<% end %>

<%= render template: "layouts/application" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="ru">
<head>
  <title>МегаАптека | Купить лекарства </title>
  <meta charset="utf-8">
  <meta name="author" content="">
  <meta name="description" content="">
  <meta name="keywords" content="">

  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">

  <link rel="shortcut icon" type="image/x-icon" href="/static/images/fav_icon.ico">

  <link href='http://fonts.googleapis.com/css?family=Roboto:400,400italic,300,300italic,700,700italic,900,900italic&subset=latin,cyrillic'
        rel='stylesheet' type='text/css'>

  <!--<link rel="stylesheet" href="/static/css/animate.css">-->
  <link rel="stylesheet" href="/static/css/fontello.css">
  <link rel="stylesheet" href="/static/css/bootstrap.min.css">

  <%= yield :stylesheets if content_for? :stylesheets %>

  <link rel="stylesheet" href="/static/js/owlcarousel/owl.carousel.css">
  <link rel="stylesheet" href="/static/js/arcticmodal/jquery.arcticmodal.css">

  <script src="/static/js/modernizr.js"></script>
  <!--[if lte IE 9]>
  <link rel="stylesheet" type="text/css" href="/static/css/oldie.css">
  <![endif]-->

  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body class="front_page">

<div class="wide_layout">
  <header id="header" class="type_4">
    <%= render partial: 'shared/header' %>
  </header>

  <% if content_for? :container %>
       <%= yield :container %>
  <% else %>
      <div class="page_wrapper">
        <div class="container">
        <%= yield %>
        </div>
      </div>
  <% end  %>

  <footer id="footer" class="type_4">
    <div class="container">
      <%= yield :footer %>
    </div>
    <%= render partial: 'shared/footer' %>
  </footer>
</div>

<%= render partial: 'shared/sidebar_buttons' %>

<script src="/static/js/jquery-2.1.1.min.js"></script>
<script src="/static/js/queryloader2.min.js"></script>
<script src="/static/js/owlcarousel/owl.carousel.min.js"></script>
<script src="/static/js/jquery.countdown.plugin.min.js"></script>
<script src="/static/js/jquery.countdown.min.js"></script>
<script src="/static/js/arcticmodal/jquery.arcticmodal.js"></script>
<script src="/static/js/colorpicker/colorpicker.js"></script>

<%= yield :javascripts if content_for? :javascripts %>

<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>

<script type="text/javascript" src="http://s7.addthis.com/js/300/addthis_widget.js"></script>

</body>
</html>

app/views/layouts/static.html.erb
<% content_for :container do %>
    <div class="secondary_page_wrapper">
      <div class="container">

        <%= render partial: "shared/breadcrumbs" %>
        <div class="row">

          <aside class="col-md-3 col-sm-4">

            <%= render partial: "sidebar_menu" %>

            <section class="section_offset">
              <h3 class="offset_title">Рассылка акций</h3>
              <%= render partial: "shared/newsletter" %>
            </section>

            <section class="section_offset">
              <h3 class="offset_title">Отзывы</h3>
              <%= render partial: "shared/testimonials" %>
            </section>

          </aside>

          <main class="col-md-9 col-sm-8">
            <%= yield %>
          </main>

        </div><!--/ .row-->

      </div>
    </div>
<% end  %>

<% content_for :stylesheets do %>
    <link rel="stylesheet" href="/static/css/jquery-ui.min.css">
<% end %>

<% content_for :javascripts do %>
    <script src="/static/js/jquery-ui.min.js"></script>
<% end %>

<% content_for :footer do %>
    <%= render partial: 'shared/features_block' %>
<% end %>

<%= render template: "layouts/application" %>

app/views/shared/_breadcrumbs.html.erb
<ul class="breadcrumbs">
  <li><a href="/">Главная</a></li>
  <li>Каталог товаров</li>
</ul>

app/views/shared/_cart_dropdown.html.erb
<div class="shopping_cart dropdown">

  <div class="animated_item">

    <p class="title">Недавно добавленные</p>

    <!-- - - - - - - - - - - - - - Product - - - - - - - - - - - - - - - - -->

    <div class="clearfix sc_product">

      <a href="#" class="product_thumb"><img src="/static/images/sc_img_1.jpg" alt=""></a>

      <a href="#" class="product_name">Aenean Auctor Wisi Et Urna Ipsum...</a>

      <p>1 x 499₴ </p>

      <button class="close"></button>

    </div><!--/ .clearfix.sc_product-->

    <!-- - - - - - - - - - - - - - End of product - - - - - - - - - - - - - - - - -->

  </div><!--/ .animated_item-->

  <div class="animated_item">

    <!-- - - - - - - - - - - - - - Product - - - - - - - - - - - - - - - - -->

    <div class="clearfix sc_product">

      <a href="#" class="product_thumb"><img src="/static/images/sc_img_2.jpg" alt=""></a>

      <a href="#" class="product_name">Lorem Ipsum Dolor Sit Amet...</a>

      <p>1 x 499₴ </p>

      <button class="close"></button>

    </div><!--/ .clearfix.sc_product-->

    <!-- - - - - - - - - - - - - - End of product - - - - - - - - - - - - - - - - -->

  </div><!--/ .animated_item-->

  <div class="animated_item">

    <!-- - - - - - - - - - - - - - Product - - - - - - - - - - - - - - - - -->

    <div class="clearfix sc_product">

      <a href="#" class="product_thumb"><img src="/static/images/sc_img_3.jpg" alt=""></a>

      <a href="#" class="product_name">Nemo Enim Ipsam <br>Voluptatem 30 ea</a>

      <p>1 x 499₴ </p>

      <button class="close"></button>

    </div><!--/ .clearfix.sc_product-->

    <!-- - - - - - - - - - - - - - End of product - - - - - - - - - - - - - - - - -->

  </div><!--/ .animated_item-->

  <div class="animated_item">

    <!-- - - - - - - - - - - - - - Total info - - - - - - - - - - - - - - - - -->

    <ul class="total_info">

      <li><span class="price">Скидка:</span> 37₴ </li>

      <li class="total"><b><span class="price">Итого:</span> 999₴ </b></li>

    </ul>

    <!-- - - - - - - - - - - - - - End of total info - - - - - - - - - - - - - - - - -->

  </div><!--/ .animated_item-->

  <div class="animated_item">
    <%= link_to 'Корзина', cart_path, class: 'button_grey' %>
    <%= link_to 'К оплате', checkout_path, class: 'button_blue' %>
  </div>

</div>

app/views/shared/_filters.html.erb
<form class="type_2">

  <div class="table_layout list_view">

    <div class="table_row">

      <!-- - - - - - - - - - - - - - Category filter - - - - - - - - - - - - - - - - -->

      <div class="table_cell">

        <label>Умный подбор</label>

        <div class="custom_select">

          <select name="">
            <option value="Лидеры продаж">Лидеры продаж</option>
            <option value="Новинки">Новинки</option>
            <option value="Акционные товары">Акционные товары</option>
            <option value="Рекомендуемые">Рекомендуемые</option>
          </select>

        </div>

      </div>
      <!--/ .table_cell -->

      <!-- - - - - - - - - - - - - - End of category filter - - - - - - - - - - - - - - - - -->

      <!-- - - - - - - - - - - - - - Manufacturer - - - - - - - - - - - - - - - - -->

      <div class="table_cell">

        <fieldset>

          <legend>Производитель</legend>

          <ul class="checkboxes_list">

            <li>
              <input type="checkbox" checked name="manufacturer" id="manufacturer_1">
              <label for="manufacturer_1">Хиноин Прайвит</label>
            </li>

            <li>
              <input type="checkbox" name="manufacturer" id="manufacturer_2">
              <label for="manufacturer_2">Пфайзер Фармасьютикалс</label>
            </li>

            <li>
              <input type="checkbox" name="manufacturer" id="manufacturer_3">
              <label for="manufacturer_3">BAYER CARE</label>
            </li>

          </ul>

        </fieldset>

      </div>
      <!--/ .table_cell -->

      <!-- - - - - - - - - - - - - - End manufacturer - - - - - - - - - - - - - - - - -->

      <!-- - - - - - - - - - - - - - Price - - - - - - - - - - - - - - - - -->

      <div class="table_cell">

        <fieldset>

          <legend>Цена</legend>

          <div class="range">
            Диапазон:
            <span class="min_val"></span> -
            <span class="max_val"></span>
            <input type="hidden" name="" class="min_value">
            <input type="hidden" name="" class="max_value">
          </div>

          <div id="slider"></div>

        </fieldset>

      </div>
      <!--/ .table_cell -->


      <!--
      <div class="table_cell">

        <fieldset>

          <legend>Color</legend>

          <div class="row">

            <div class="col-sm-6">

              <ul class="simple_vertical_list">

                <li>

                  <input type="checkbox" name="" id="color_btn_1">
                  <label for="color_btn_1" class="color_btn green">Green</label>

                </li>

                <li>

                  <input type="checkbox" name="" id="color_btn_2">
                  <label for="color_btn_2" class="color_btn yellow">Yellow</label>

                </li>

                <li>

                  <input type="checkbox" name="" id="color_btn_3">
                  <label for="color_btn_3" class="color_btn red">Red</label>

                </li>

              </ul>

            </div>

            <div class="col-sm-6">

              <ul class="simple_vertical_list">

                <li>

                  <input type="checkbox" name="" id="color_btn_4">
                  <label for="color_btn_4" class="color_btn blue">Blue</label>

                </li>

                <li>

                  <input type="checkbox" name="" id="color_btn_5">
                  <label for="color_btn_5" class="color_btn grey">Grey</label>

                </li>

                <li>

                  <input type="checkbox" name="" id="color_btn_6">
                  <label for="color_btn_6" class="color_btn orange">Orange</label>

                </li>

              </ul>

            </div>

          </div>

        </fieldset>

      </div>
      <!--/ .table_cell -->


      <!-- - - - - - - - - - - - - - End price - - - - - - - - - - - - - - - - -->

    </div>
    <!--/ .table_row -->

  </div>
  <!--/ .table_layout -->

  <footer class="bottom_box">
    <div class="buttons_row">
      <button type="submit" class="button_blue middle_btn">Поиск</button>
      <button type="reset" class="button_grey middle_btn filter_reset">Сбросить</button>
    </div>

  </footer>

</form>

app/views/shared/_header.html.erb
<div id="topbar_menu">&nbsp;</div>

<div class="bottom_part">

  <div class="container">

    <div class="row">

      <div class="main_header_row">

        <div class="col-sm-7">
          <!-- - - - - - - - - - - - - - Logo - - - - - - - - - - - - - - - - -->
          <a href="/" class="logo">
            <img src="/static/images/logo_v2-large@2x.png" alt="Мега Аптека Здоровья">
          </a>
        </div>
        <!--/ [col]-->

        <div class="col-lg-5 col-sm-5">

          <div class="clearfix">

            <!-- - - - - - - - - - - - - - Language change - - - - - - - - - - - - - - - - -->

            <div class="alignright site_settings">

              <span class="label">Выбран язык</span> <span class="current open_">
                 <!-- <img src="/static/images/flags/RU.png" alt="">-->Русский</span>

              <ul class="dropdown site_setting_list language" style="width: 130px;">
                <li><a href="#"><!--<img src="/static/images/flags/RU.png" alt="">-->Русский</a></li>
                <li><a href="#"><!--<img src="/static/images/flags/UA.png" alt="">-->Українська</a></li>
              </ul>

            </div>
            <!--/ .alignright.site_settings-->


            <div class="alignright site_settings">

              <span class="label">Ваш город</span> <span class="current open_">Киев</span>

              <ul class="dropdown site_setting_list city">

                <li class="animated_item"><a href="#">Харьков</a></li>
                <li class="animated_item"><a href="#">Одесса</a></li>
                <li class="animated_item"><a href="#">Николаев</a></li>

              </ul>

            </div>


          </div>
          <!--/ .clearfix-->

          <!-- - - - - - - - - - - - - - Navigation of shop - - - - - - - - - - - - - - - - -->

          <nav class="align_right">
            <ul class="topbar">
              <li><a href="#">Наши аптеки</a></li>
              <li><%= link_to 'Как сделать заказ', how_to_path %></li>
              <li><%= link_to 'Гарантия', warranty_path %></li>
              <li><%= link_to 'Контакты', contacts_path %></li>
              <!--<li><a href="#">Баланс карты</a></li>-->
            </ul>
          </nav>

        </div>
        <!--/ [col]-->

      </div>
      <!--/ .main_header_row-->

    </div>
    <!--/ .row-->

  </div>
  <!--/ .container-->

</div>
<!--/ .bottom_part -->

<!-- - - - - - - - - - - - - - Main navigation wrapper - - - - - - - - - - - - - - - - -->
<div id="main_navigation_wrap">

  <div class="container">

    <div class="row">

      <div class="col-xs-12">

        <div class="sticky_inner">

          <!-- - - - - - - - - - - - - - Categories menu - - - - - - - - - - - - - - - - -->
          <div class="nav_item size_1">

            <button class="open_menu"></button>

            <%= render partial: 'shared/categories_menu',
                       locals: {is_dropdown: true} %>

          </div>
          <!--/ .nav_item-->

          <!-- - - - - - - - - - - - - - Search form - - - - - - - - - - - - - - - - -->
          <div class="nav_item inner_offset">
            <%= render 'shared/search_form' %>
          </div>
          <!--/ .nav_item-->

          <!-- - - - - - - - - - - - - - Wishlist btn - - - - - - - - - - - - - - - - -->
          <div class="nav_item size_1">
            <%= link_to '', account_wishlist_path, class: 'wishlist_button', 'data-amount': 7 %>
          </div>
          <!--/ .nav_item-->

          <!-- - - - - - - - - - - - - - Compare btn - - - - - - - - - - - - - - - - -->
          <div class="nav_item size_1">
            <%= link_to '', compare_path, class: 'compare_button', 'data-amount': 3 %>
          </div>
          <!--/ .nav_item-->

          <!-- - - - - - - - - - - - - - Login block - - - - - - - - - - - - - - - - -->
          <div class="nav_item size_2">

            <div class="login_box">
              <div class="login_box_inner">Приветствуем
                <a href="<%= login_path %>" data-modal-url="<%= login_path %>">Авторизоваться</a></a>
              </div>
            </div>

          </div>
          <!--/ .nav_item-->

          <!-- - - - - - - - - - - - - - Cart  - - - - - - - - - - - - - - - - -->
          <div class="nav_item size_2">

            <button id="open_shopping_cart" class="open_button" data-amount="3">
              <b class="title">Корзина</b>
              <b class="total_price">999 грн.</b>
            </button>

            <%= render partial: 'shared/cart_dropdown' %>
          </div>
          <!--/ .nav_item-->

        </div>
        <!--/ .main_navigation-->

      </div>
      <!--/ [col]-->

    </div>
    <!--/ .row-->

  </div>
  <!--/ .container-->

</div>
<!--/ .main_navigation_wrap-->

app/views/shared/_newsletter.html.erb
<div class="theme_box">
  <p class="form_caption">Подпишитесь на рассылку акционных предложений и новинок от Мега Аптеки!</p>
  <form class="newsletter subscribe clearfix" novalidate>
    <input type="email" name="sc_email" placeholder="Введите свой email">
    <button class="button_blue def_icon_btn"></button>
  </form>
</div>

app/views/shared/_product_item.html.erb
<div class="product_item">
  <div class="image_wrap">
    <img src="/static/images/product_img_<%= rand(1..33) %>.jpg" alt="">

    <div class="actions_wrap">
      <div class="centered_buttons">
        <a href="#" class="button_dark_grey middle_btn quick_view"
           data-modal-url="<%= product_view_path %>">Подробно</a>
        <a href="#" class="button_blue middle_btn add_to_cart">В корзину</a>
      </div>
      <!--/ .centered_buttons -->

      <a href="#"
         class="button_dark_grey def_icon_btn middle_btn add_to_wishlist tooltip_container">
        <span class="tooltip right">Отложить</span>
      </a>

      <a href="#"
         class="button_dark_grey def_icon_btn middle_btn add_to_compare tooltip_container">
        <span class="tooltip left">К сравнению</span>
      </a>

    </div>
    <!--/ .actions_wrap-->
  </div>
  <!--/. image_wrap-->

  <!-- - - - - - - - - - - - - - Label - - - - - - - - - - - - - - - - -->
  <div class="<%= label_class %>">
    <%= raw label_text %>
  </div>

  <% if with_countdown  %>
      <div class="countdown"
           data-year="2016"
           data-month="01"
           data-day="<%= rand(18..30) %>"
           data-hours="15"
           data-minutes="0"
           data-seconds="0">
      </div>
  <% end  %>

  <!-- - - - - - - - - - - - - - Product description - - - - - - - - - - - - - - - - -->
  <div class="description">
    <p><a href="#">Tellus Dolor Dapibus Eget 24 fl oz</a></p>

    <div class="clearfix product_info">
      <!-- - - - - - - - - - - - - - Product rating - - - - - - - - - - - - - - - - -->
      <ul class="rating alignright">

        <li class="active"></li>
        <li class="active"></li>
        <li class="active"></li>
        <li class="active"></li>
        <li></li>

      </ul>

      <p class="product_price alignleft"><s>9.99</s> <b>5.99</b></p>
    </div>
    <!--/ .clearfix.product_info-->
  </div>

  <% if with_full_description %>
  <!-- - - - - - - - - - - - - - Full description (only for list view) - - - - - - - - - - - - - - - - -->
  <div class="full_description">

    <a href="#" class="product_title">Sed ut perspiciatis unde, Liqui-gels 24 capsules</a>
    <a href="#" class="product_category">Косметика</a>

    <div class="v_centered product_reviews">

      <!-- - - - - - - - - - - - - - Product rating - - - - - - - - - - - - - - - - -->
      <ul class="rating">
        <li class="active"></li>
        <li class="active"></li>
        <li class="active"></li>
        <li class="active"></li>
        <li></li>
      </ul>

      <!-- - - - - - - - - - - - - - Reviews menu - - - - - - - - - - - - - - - - -->
      <ul class="topbar">
        <li><a href="#">3 отзыва</a></li>
        <li><a href="#">Оставить отзыв</a></li>
      </ul>

    </div>

    <p>Mauris accumsan nulla vel diam. Sed in lacus ut enim adipiscing aliquet.
      Nulla venenatis. In pede mi, aliquet sit amet, euismod in, auctor ut, ligula.</p>

    <a href="#" class="learn_more">На карточку товара</a>
  </div>

  <!-- - - - - - - - - - - - - - Product price & actions (only for list view) - - - - - - - - - - - - - - - - -->
  <div class="actions">

    <p class="product_price bold"><%= rand(50..500) %>.99</p>

    <ul class="seller_stats">

      <li>Код товара: <span class="success"><%= rand(1000-2000) %></span></li>
      <li>В наличии: <span class="success"><%= rand(5..10) %> ед.</span></li>

      <li class="seller_info_wrap">

        <span class="seller_name">Подробно</span>

        <div class="seller_info_dropdown">
          <ul class="seller_stats">
            <li>
              <ul class="topbar">
                <li>Код АТС</li>
                <li><a href="#">J01XD01</a></li>
              </ul>
            </li>
            <li><span class="bold">Форма выпуска</span> - таблетки в блистере по 250мг</li>
          </ul>

          <div class="v_centered">
            <a href="#" class="button_blue mini_btn">Уточнить наличие</a>
            <a href="#" class="small_link">Аналоги</a>
          </div>
        </div>

      </li>

    </ul>

    <ul class="buttons_col">
      <li><a href="#" class="button_blue middle_btn add_to_cart">В корзину</a></li>
      <li><a href="#" class="icon_link"><i class="icon-heart-5"></i>Отложить</a></li>
      <li><a href="#" class="icon_link"><i class="icon-resize-small"></i>Сравнить</a></li>
    </ul>

  </div>
  <% end  %>

</div>
<!--/ .product_item-->

app/views/shared/_products_section.html.erb
<section class="section_offset">

  <h3 class="section_title"><%= title %></h3>

  <div class="tabs type_2 products">
    <% md5 = Digest::MD5.new; md5 << title; pref = md5.hexdigest.to_s[0..4] %>
    <ul class="tabs_nav clearfix">
      <li><a href="#<%= pref %>_tab-1">Лекарства</a></li>
      <li><a href="#<%= pref %>_tab-2">Красота</a></li>
      <li><a href="#<%= pref %>_tab-3">Мама и малыш</a></li>
      <li><a href="#<%= pref %>_tab-4">Лечебная косметика</a></li>
      <li><a href="#<%= pref %>_tab-5">Медтехника и изделия</a></li>
      <li><a href="#<%= pref %>_tab-6">Товары для здоровья</a></li>
      <li><a href="#<%= pref %>_tab-7">БАДы и витамины</a></li>
    </ul>

    <div class="tab_containers_wrap">

      <% 7.times do |tab|  %>
      <div id="<%= pref %>_tab-<%= tab+1 %>" class="tab_container">
        <div class="owl_carousel carousel_in_tabs type_2">

          <% 5.times do %>
            <%= render partial: 'shared/product_item',
                       locals: {
                               label_class: label_class,
                               label_text: label_text,
                               with_countdown: with_countdown,
                               with_full_description: false
                       } %>
          <% end  %>

        </div>
        <!--/ .owl_carousel-->
      </div>
      <% end  %>

    </div>

  </div>

</section>
<!--/ .section_offset-->

app/views/shared/_rating.html.erb
<ul class="rating">
  <li class="active"></li>
  <li class="active"></li>
  <li class="active"></li>
  <li></li>
  <li></li>
</ul>

app/views/shared/_reviews.html.erb
<ul class="topbar">
  <li><a href="#">3 отзыва</a></li>
  <li><a href="#">Оставить отзыв</a></li>
</ul>